---
title: "ReadMe UNGDC"
output: html_document
---

# Purpose

This README describes the metadata for the **United Nations General Debate Corpus**. The dataset contains speeches delivered during the UN General Debates from 1946 to 2025. However, this project examines only speeches from 1989 to 2000, inclusive.

# Data Source

The data were accessed on 18 August 2026. We use the latest available release **Version 14 (March 2026)** which covers 80 UN General Debate sessions.

- [United Nations General Debate Corpus, 1946–2025](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/0TJX8Y)

The dataset webpage has also been archived using the **Internet Archive's Wayback Machine**.

# Files and Format

The complete corpus contains **11,141 speeches**, stored as UTF-8-encoded plain-text (`.txt`) files.

The speeches were derived from audio recordings or transcripts obtained from [gadebate.un.org](https://gadebate.un.org/). Audio recordings were transcribed using OpenAI's `whisper-1` model.

# Unit of Observation and Identification

The unit of observation is an individual speech. According to the corpus's original README:

> Speeches are structured by year (session). Each speech is named using the following convention: ISO 3166-1 alpha-3 country code, followed by the UN session number, followed by the year. For example, `USA_75_2020.txt`.[^1]

# Citation

[^1]: Jankin, S., Baturo, A., & Dasandi, N. (2025). Words to unite nations: The complete United Nations General Debate Corpus, 1946–present. *Journal of Peace Research, 62*(4), 1339–1351.
